language: android
android:
  components:
    - build-tools-29.0.0
    - android-29
    - extra

test:
  pre:
    # Create mock Play Services JSON
    - ./team-props/scripts/ci-mock-google-services-setup.sh

  override:
    - ./gradlew check --no-daemon --console=plain --continue
